project:
  type: website

website:
  title: "Tanmoy Biswas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv/
        text: "CV"
    right:
      - icon: github
        href: https://github.com/Tanmoy-data-science
        aria-label: GitHub
        target: _blank
        rel: noopener
      - icon: linkedin
        href: https://www.linkedin.com/in/tanmoy-biswas7/
        aria-label: LinkedIn
        target: _blank
        rel: noopener
  favicon: assets/favicon.png
  page-footer: "© 2025 Tanmoy Biswas"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
metadata:
  description: "Portfolio & coursework in data visualization and analytics."
  site-url: https://Tanmoy-data-science.github.io
  open-graph: true
  twitter-card: true
  image: images/og-image.png
