project:
  type: website

website:
  title: "Tanmoy Biswas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv/
        text: "CV"
    right:
      - icon: github
        href: https://github.com/Tanmoy-data-science
        aria-label: GitHub
      - icon: linkedin
        href: https://www.linkedin.com/in/YOUR-LINKEDIN/
        aria-label: LinkedIn
  favicon: assets/favicon.png
  page-footer: "© 2025 Tanmoy Biswas"

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true
