project:
  type: website
  render:
    - index.qmd
    - about.qmd
    - cv/index.qmd
    - assignments/knowledge-mining/index.qmd
    - assignments/knowledge-mining/assignment02/assignment02.qmd
    - assignments/knowledge-mining/assignment03/assignment03.qmd
    - assignments/knowledge-mining/assignment04/assignment04.qmd

execute:
  freeze: auto
  
website:
  title: "Tanmoy Biswas"
  favicon: assets/favicon.png
  page-footer: "© 2025 Tanmoy Biswas"
  navbar:
    left:
      - href: index.qmd
        text: Home
      - href: cv/index.qmd
        text: "My Bio"
      - href: assignments/knowledge-mining/index.qmd
        text: "Assignments"
    right:
      - icon: github
        href: https://github.com/Tanmoy-data-science
        aria-label: GitHub
        target: _blank
        rel: noopener
      - icon: linkedin
        href: https://www.linkedin.com/in/tanmoy-biswas7/
        aria-label: LinkedIn
        target: _blank
        rel: noopener

format:
  html:
    theme: cosmo
    css: styles.css
    toc: true

metadata:
  description: "Portfolio & coursework in data visualization and analytics."
  site-url: https://Tanmoy-data-science.github.io
  open-graph: true
  twitter-card: true
  image: assets/headshot.jpg